"""AnalysisReport: a human-readable summary produced from a window of logs/alerts."""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import UTC, datetime
from uuid import UUID, uuid4


@dataclass(frozen=True, slots=True)
class AnalysisReport:
    """A natural-language incident summary generated by the AI analysis port.

    `period_start`/`period_end` describe the log window the report
    covers. `s3_object_key` is populated once the report (and the raw
    logs behind it) has been archived to object storage, and is `None`
    until that happens.
    """

    id: UUID
    summary: str
    period_start: datetime
    period_end: datetime
    alert_ids: list[UUID]
    generated_at: datetime = field(default_factory=lambda: datetime.now(UTC))
    s3_object_key: str | None = None

    @classmethod
    def new(
        cls,
        summary: str,
        period_start: datetime,
        period_end: datetime,
        alert_ids: list[UUID],
    ) -> AnalysisReport:
        return cls(
            id=uuid4(),
            summary=summary,
            period_start=period_start,
            period_end=period_end,
            alert_ids=alert_ids,
        )
